# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/ip/cnt_mod120k/cnt_mod120k.xci
# IP: The module: 'cnt_mod120k' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/ip/cnt_mod120k/cnt_mod120k_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cnt_mod120k'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/ip/cnt_mod120k/cnt_mod120k.xci
# IP: The module: 'cnt_mod120k' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/ip/cnt_mod120k/cnt_mod120k_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cnt_mod120k'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
