# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Archivos sesión 2-20210922/Nexys4DDR_Master.xdc

# IP: ip/cnt_mod99/cnt_mod99.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cnt_mod99 || ORIG_REF_NAME==cnt_mod99}]

# IP: ip/ram/ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ram || ORIG_REF_NAME==ram}]

# IP: ip/clk_12megas/clk_12megas.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_12megas || ORIG_REF_NAME==clk_12megas}]
