# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.cache/wt [current_project]
set_property parent.project_path C:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo c:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/imports/new/package_dsed.vhd
  C:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/new/audio_interface.vhd
  C:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/new/bcd_7seg.vhd
  C:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/new/bin7_bcd2.vhd
  C:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/new/ctrl_fir.vhd
  C:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/new/data_flux_fir.vhd
  C:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/new/en_4_cycles.vhd
  C:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/new/fir_filter.vhd
  C:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/new/fsmd_main.vhd
  C:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/new/fsmd_microphone.vhd
  C:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/new/matrix_blinker.vhd
  C:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/new/matrix_driver.vhd
  C:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/new/mux5.vhd
  C:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/new/mux7.vhd
  C:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/new/mux8x7.vhd
  C:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/new/pwm.vhd
  C:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/new/state_7seg.vhd
  C:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/new/vol_ctl.vhd
  C:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/new/main.vhd
}
read_ip -quiet C:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/ip/cnt_mod99/cnt_mod99.xci
set_property used_in_implementation false [get_files -all c:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/ip/cnt_mod99/cnt_mod99_ooc.xdc]
set_property is_locked true [get_files C:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/ip/cnt_mod99/cnt_mod99.xci]

read_ip -quiet C:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/ip/ram/ram.xci
set_property used_in_implementation false [get_files -all c:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/ip/ram/ram_ooc.xdc]
set_property is_locked true [get_files C:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/ip/ram/ram.xci]

read_ip -quiet C:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/ip/clk_12megas/clk_12megas.xci
set_property used_in_implementation false [get_files -all c:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/ip/clk_12megas/clk_12megas_board.xdc]
set_property used_in_implementation false [get_files -all c:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/ip/clk_12megas/clk_12megas.xdc]
set_property used_in_implementation false [get_files -all c:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/ip/clk_12megas/clk_12megas_ooc.xdc]
set_property is_locked true [get_files C:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/ip/clk_12megas/clk_12megas.xci]

read_ip -quiet C:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/ip/cnt_mod120k/cnt_mod120k.xci
set_property used_in_implementation false [get_files -all c:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/ip/cnt_mod120k/cnt_mod120k_ooc.xdc]
set_property is_locked true [get_files C:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/sources_1/ip/cnt_mod120k/cnt_mod120k.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/constrs_1/imports/Archivos sesión 2-20210922/Nexys4DDR_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/home/archivos_dsed_lab/dsed_audiobox/dsed_audiobox.srcs/constrs_1/imports/Archivos sesión 2-20210922/Nexys4DDR_Master.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top main -part xc7a100tcsg324-1


write_checkpoint -force -noxdef main.dcp

catch { report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb }
